# =============================================================================
# baseline_cf.py
# CS 550 - Massive Data Mining | Movie Recommender System
# =============================================================================
# PURPOSE:
#   Implements the BASELINE recommender algorithm using classical Memory-Based
#   User-User Collaborative Filtering (CF) with Cosine Similarity.
#
#   This script serves as the performance benchmark. Its results are compared
#   directly against the SVD approach in my_svd_approach.py to demonstrate
#   the limitations of memory-based methods on sparse data.
#
# ALGORITHM OVERVIEW:
#   1. Build a User-Item rating matrix from training data
#   2. Compute pairwise Cosine Similarity between all users
#   3. Predict ratings using a similarity-weighted average of neighbor ratings
#   4. Evaluate rating accuracy (MAE, RMSE) on held-out test ratings
#   5. Generate Top-10 recommendation lists and evaluate ranking quality
#      (Precision@10, Recall@10, F1-Measure, NDCG@10)
#
# INPUT:
#   processed/train_ratings.csv  (generated by data_prep.py)
#   processed/test_ratings.csv   (generated by data_prep.py)
#
# OUTPUT:
#   Prints MAE, RMSE, Precision@10, Recall@10, F1, NDCG@10 to console
#
# RUN:
#   python baseline_cf.py
#   NOTE: Run data_prep.py first to generate the processed/ directory.
# =============================================================================

import os
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics import mean_squared_error, mean_absolute_error
from tqdm import tqdm


# -----------------------------------------------------------------------------
# HELPER FUNCTIONS: DCG and NDCG
# -----------------------------------------------------------------------------

def dcg_at_k(r, k):
    """
    Computes Discounted Cumulative Gain (DCG) at rank k.

    DCG rewards relevant items appearing early in the ranked list.
    Items at rank 1 contribute more than items at rank 10 via the
    log2 discount factor in the denominator.

    Formula: DCG@k = sum( rel_i / log2(i + 1) ) for i = 1..k

    Args:
        r (list): Relevance scores in ranked order (1 = hit, 0 = miss).
        k (int) : Cutoff rank (10 in our evaluation).

    Returns:
        float: The DCG score.
    """
    r = np.asarray(r, dtype=float)[:k]   # truncate to top-k
    if r.size:
        return np.sum(r / np.log2(np.arange(2, r.size + 2)))
    return 0.


def ndcg_at_k(r, k):
    """
    Computes Normalized Discounted Cumulative Gain (NDCG) at rank k.

    Normalizes DCG by the Ideal DCG (IDCG) — the score you would get
    if all hits were placed at the very top of the list. This produces
    a value in [0, 1] that is comparable across users with different
    numbers of test items.

    Formula: NDCG@k = DCG@k / IDCG@k

    Args:
        r (list): Relevance scores in ranked order (1 = hit, 0 = miss).
        k (int) : Cutoff rank.

    Returns:
        float: NDCG score in [0, 1]. Returns 0 if no relevant items exist.
    """
    idcg = dcg_at_k(sorted(r, reverse=True), k)   # best possible ordering
    if not idcg:
        return 0.
    return dcg_at_k(r, k) / idcg


# -----------------------------------------------------------------------------
# MAIN FUNCTION
# -----------------------------------------------------------------------------

def run_baseline_cf():
    """
    Full pipeline for the User-User Collaborative Filtering baseline:
    loads data, builds the similarity model, evaluates rating prediction
    accuracy, and evaluates Top-10 recommendation ranking quality.
    """

    # Anchor all paths to the script's location on disk so the script works
    # regardless of which directory the user runs it from
    project_dir   = os.path.dirname(os.path.abspath(__file__))
    processed_dir = os.path.join(project_dir, 'processed')
    ml_dir        = os.path.join(project_dir, 'ml-latest-small')  # available for future use

    # -------------------------------------------------------------------------
    # STEP 1: Load train and test splits produced by data_prep.py
    # -------------------------------------------------------------------------
    print("Loading datasets...")
    train_df = pd.read_csv(os.path.join(processed_dir, 'train_ratings.csv'))
    test_df  = pd.read_csv(os.path.join(processed_dir, 'test_ratings.csv'))

    # -------------------------------------------------------------------------
    # STEP 2: Build the User-Item Pivot Matrix
    # -------------------------------------------------------------------------
    # Rows = users, Columns = movies, Values = ratings (NaN where unrated).
    # This matrix is ~98% sparse — most users have rated only a tiny fraction
    # of the ~9,700 available movies. This sparsity is the core challenge
    # that the baseline algorithm struggles with.
    print("Building User-Item Pivot Matrix...")
    R_df   = train_df.pivot(index='userId', columns='movieId', values='rating')
    users  = R_df.index.tolist()
    movies = R_df.columns.tolist()

    # -------------------------------------------------------------------------
    # STEP 3: Compute User-User Cosine Similarity
    # -------------------------------------------------------------------------
    # NaN values (unrated movies) are filled with 0 before computing similarity.
    # This is the standard practice for memory-based CF — treating unrated as
    # neutral rather than as a zero-star rating.
    #
    # Cosine similarity formula:
    #   sim(u, v) = (r_u · r_v) / (||r_u|| * ||r_v||)
    #
    # Result is a (610 x 610) symmetric matrix where entry [u, v] is the
    # similarity score between user u and user v, ranging from 0 to 1.
    print("Calculating User-User Cosine Similarity...")
    R_filled          = R_df.fillna(0)
    user_similarity   = cosine_similarity(R_filled)
    user_similarity_df = pd.DataFrame(user_similarity, index=users, columns=users)

    # -------------------------------------------------------------------------
    # STEP 4: Rating Prediction — MAE and RMSE Evaluation
    # -------------------------------------------------------------------------
    # For each (user, movie) pair in the test set, predict the rating using
    # the weighted average formula:
    #
    #   r_hat(u, i) = sum( sim(u,v) * r(v,i) ) / sum( sim(u,v) )
    #                 for all users v who have rated movie i
    #
    # Fallback hierarchy when neighbors are unavailable:
    #   1. User's own mean rating (personalised fallback)
    #   2. Global mean rating across all training ratings (last resort)
    print("\n--- Evaluating Rating Accuracy (MAE/RMSE) ---")
    actuals     = []
    predictions = []
    global_mean = train_df['rating'].mean()

    # Pre-compute each user's mean rating for use in fallback predictions
    user_means = R_df.mean(axis=1)

    print("Predicting test ratings...")
    for _, row in test_df.iterrows():
        u      = row['userId']
        i      = row['movieId']
        actual = row['rating']

        if u in user_similarity_df.index and i in R_df.columns:

            # Retrieve this user's similarity scores against all other users
            sims = user_similarity_df.loc[u].copy()

            # Only keep similarities for users who have actually rated movie i
            # (users with NaN for movie i cannot contribute to the prediction)
            rated_by   = R_df[i].dropna()
            sim_scores = sims.loc[rated_by.index]

            # Weighted average prediction — more similar neighbors have
            # proportionally more influence on the predicted rating
            if len(sim_scores) > 0 and sim_scores.sum() > 0:
                weighted_sum = np.dot(sim_scores, rated_by)
                pred         = weighted_sum / sim_scores.sum()
            else:
                # Fallback: no neighbours rated this movie
                pred = user_means[u] if pd.notna(user_means[u]) else global_mean
        else:
            # Fallback: user or movie not seen during training
            pred = global_mean

        # Clip predictions to the valid MovieLens rating scale [0.5, 5.0]
        pred = max(0.5, min(5.0, pred))

        actuals.append(actual)
        predictions.append(pred)

    # MAE: average absolute error — intuitive "stars off target" metric
    # RMSE: penalises large errors more heavily than MAE due to squaring
    mae  = mean_absolute_error(actuals, predictions)
    rmse = np.sqrt(mean_squared_error(actuals, predictions))
    print(f"Baseline CF MAE:  {mae:.4f}")
    print(f"Baseline CF RMSE: {rmse:.4f}")

    # -------------------------------------------------------------------------
    # STEP 5: Top-10 Recommendation — Ranking Quality Evaluation
    # -------------------------------------------------------------------------
    # For each user, generate a ranked list of 10 movies they have NOT seen
    # in training, then check how many of those 10 appear in the test set
    # (the movies we held out). These "hits" drive all four ranking metrics.
    print("\n--- Evaluating Top-10 Ranking Metrics ---")
    user_train_items = train_df.groupby('userId')['movieId'].apply(set).to_dict()
    user_test_items  = test_df.groupby('userId')['movieId'].apply(set).to_dict()

    precisions, recalls, ndcgs = [], [], []
    all_items = set(movies)   # full set of movies seen during training

    print("Generating candidate recommendations...")
    for user_id, test_items in tqdm(user_test_items.items()):

        # Skip users not present in the similarity matrix
        if user_id not in user_similarity_df.index:
            continue

        # Candidate pool = all training movies MINUS what this user already rated.
        # We must never recommend a movie the user has already seen.
        train_items      = user_train_items.get(user_id, set())
        candidate_items  = list(all_items - train_items)

        if not candidate_items:
            continue

        # -----------------------------------------------------------------
        # Vectorised prediction for all candidate items at once
        # (much faster than looping over each movie individually)
        # -----------------------------------------------------------------

        # Shape: (1,) vector of this user's similarities to all other users
        sims = user_similarity_df.loc[user_id].values

        # Slice the filled rating matrix to only candidate columns
        # Shape: (num_users, num_candidate_items)
        ratings_candidate = R_filled[candidate_items].values

        # Binary mask: 1 where a user has rated the movie, 0 where they haven't
        # Used to compute the denominator (sum of similarities for raters only)
        rated_mask = (ratings_candidate > 0).astype(float)
        sim_sums   = sims.dot(rated_mask)       # effective similarity mass per movie

        # Numerator: similarity-weighted sum of ratings per candidate movie
        weighted_ratings = sims.dot(ratings_candidate)

        # Final predictions — avoid division by zero with the idx mask
        pred_ratings       = np.zeros_like(weighted_ratings)
        idx                = sim_sums > 0
        pred_ratings[idx]  = weighted_ratings[idx] / sim_sums[idx]
        pred_ratings[~idx] = user_means[user_id] if pd.notna(user_means[user_id]) else global_mean

        # Pick the top 10 highest predicted candidates
        top_indices  = np.argsort(pred_ratings)[::-1][:10]
        top_item_ids = np.array(candidate_items)[top_indices]

        # -----------------------------------------------------------------
        # Compute per-user ranking metrics
        # -----------------------------------------------------------------

        # hits[i] = 1 if the movie recommended at rank i+1 is in the test set
        hits = [1 if item in test_items else 0 for item in top_item_ids]

        # Precision@10: fraction of the 10 recommendations that were correct
        precision = sum(hits) / 10.0

        # Recall@10: fraction of the user's test movies that were surfaced
        recall    = sum(hits) / len(test_items)

        # NDCG@10: ranking-aware metric — hits at rank 1 score higher than
        # hits at rank 10 (see dcg_at_k / ndcg_at_k above)
        ndcg      = ndcg_at_k(hits, 10)

        precisions.append(precision)
        recalls.append(recall)
        ndcgs.append(ndcg)

    # -------------------------------------------------------------------------
    # STEP 6: Aggregate and Print Final Metrics
    # -------------------------------------------------------------------------
    avg_precision = np.mean(precisions)
    avg_recall    = np.mean(recalls)

    # F1-Measure: harmonic mean of precision and recall.
    # Uses harmonic mean (not arithmetic) to penalise large imbalances
    # between the two — a model with perfect precision but zero recall
    # gets F1 = 0, not 0.5.
    avg_f1   = 2 * (avg_precision * avg_recall) / (avg_precision + avg_recall) \
               if (avg_precision + avg_recall) > 0 else 0
    avg_ndcg = np.mean(ndcgs)

    print("\n========= BASELINE CF RECOMMENDATION METRICS =========")
    print(f"Precision@10 : {avg_precision:.4f}")
    print(f"Recall@10    : {avg_recall:.4f}")
    print(f"F1-Measure   : {avg_f1:.4f}")
    print(f"NDCG@10      : {avg_ndcg:.4f}")
    print("======================================================")


# -----------------------------------------------------------------------------
# ENTRY POINT
# -----------------------------------------------------------------------------
if __name__ == '__main__':
    run_baseline_cf()