# =============================================================================
# my_svd_approach.py
# CS 550 - Massive Data Mining | Movie Recommender System
# =============================================================================
# PURPOSE:
#   Implements the ADVANCED recommender algorithm using Model-Based Matrix
#   Factorization via Singular Value Decomposition (SVD).
#
#   This is the primary algorithm of the project. It directly addresses the
#   data sparsity problem that cripples the memory-based baseline in
#   baseline_cf.py by decomposing the rating matrix into dense latent factors
#   that generalise to unseen user-movie pairs.
#
# ALGORITHM OVERVIEW:
#   1. Build a User-Item rating matrix from training data
#   2. Mean-center the matrix (subtract each user's average rating)
#   3. Apply Truncated SVD to decompose the matrix into k=50 latent factors
#   4. Reconstruct a fully-dense predicted rating matrix
#   5. Evaluate rating accuracy (MAE, RMSE) on held-out test ratings
#   6. Generate Top-10 recommendation lists and evaluate ranking quality
#      (Precision@10, Recall@10, F1-Measure, NDCG@10)
#
# MATHEMATICAL CORE:
#   R_demeaned ≈ U · Σ · Vᵀ
#   R_predicted = U · Σ · Vᵀ + user_means
#
#   Where:
#     U     : (users  × k) — each row is a user's latent factor vector
#     Σ     : (k      × k) — diagonal matrix of singular values (importance
#                            of each latent dimension)
#     Vᵀ    : (k × movies) — each column is a movie's latent factor vector
#     k=50  : number of latent factors retained (hyperparameter)
#
# INPUT:
#   processed/train_ratings.csv  (generated by data_prep.py)
#   processed/test_ratings.csv   (generated by data_prep.py)
#
# OUTPUT:
#   Prints MAE, RMSE, Precision@10, Recall@10, F1, NDCG@10 to console
#
# RUN:
#   python my_svd_approach.py
#   NOTE: Run data_prep.py first to generate the processed/ directory.
# =============================================================================

import os
import pandas as pd
import numpy as np
from scipy.sparse.linalg import svds
from sklearn.metrics import mean_squared_error, mean_absolute_error
from tqdm import tqdm


# -----------------------------------------------------------------------------
# HELPER FUNCTIONS: DCG and NDCG
# -----------------------------------------------------------------------------

def dcg_at_k(r, k):
    """
    Computes Discounted Cumulative Gain (DCG) at rank k.

    DCG rewards relevant items appearing early in the ranked list.
    Items at rank 1 contribute more than items at rank 10 via the
    log2 discount factor in the denominator.

    Formula: DCG@k = sum( rel_i / log2(i + 1) ) for i = 1..k

    Args:
        r (list): Relevance scores in ranked order (1 = hit, 0 = miss).
        k (int) : Cutoff rank (10 in our evaluation).

    Returns:
        float: The DCG score.
    """
    r = np.asarray(r, dtype=float)[:k]   # truncate to top-k positions
    if r.size:
        return np.sum(r / np.log2(np.arange(2, r.size + 2)))
    return 0.


def ndcg_at_k(r, k):
    """
    Computes Normalized Discounted Cumulative Gain (NDCG) at rank k.

    Normalizes DCG by the Ideal DCG (IDCG) — the score achieved if all
    hits were placed at the very top of the list. This produces a value
    in [0, 1] that is comparable across users with different numbers of
    test items.

    Formula: NDCG@k = DCG@k / IDCG@k

    Args:
        r (list): Relevance scores in ranked order (1 = hit, 0 = miss).
        k (int) : Cutoff rank.

    Returns:
        float: NDCG score in [0, 1]. Returns 0 if no relevant items exist.
    """
    idcg = dcg_at_k(sorted(r, reverse=True), k)   # ideal (best possible) DCG
    if not idcg:
        return 0.
    return dcg_at_k(r, k) / idcg


# -----------------------------------------------------------------------------
# MAIN FUNCTION
# -----------------------------------------------------------------------------

def run_custom_svd():
    """
    Full SVD-based recommendation pipeline:
    loads data, builds and decomposes the rating matrix, reconstructs
    dense predictions, then evaluates both rating accuracy and Top-10
    ranking quality.
    """

    # Anchor all paths to the script's location on disk so the script works
    # regardless of which directory the user runs it from
    project_dir   = os.path.dirname(os.path.abspath(__file__))
    processed_dir = os.path.join(project_dir, 'processed')
    ml_dir        = os.path.join(project_dir, 'ml-latest-small')  # available for future use

    # -------------------------------------------------------------------------
    # STEP 1: Load train and test splits produced by data_prep.py
    # -------------------------------------------------------------------------
    print("Loading datasets...")
    train_df = pd.read_csv(os.path.join(processed_dir, 'train_ratings.csv'))
    test_df  = pd.read_csv(os.path.join(processed_dir, 'test_ratings.csv'))

    # -------------------------------------------------------------------------
    # STEP 2: Build the User-Item Pivot Matrix
    # -------------------------------------------------------------------------
    # Rows = users, Columns = movies, Values = ratings.
    # Cells with no rating are NaN — the matrix is ~98% sparse.
    # SVD will address this sparsity by finding the underlying low-rank
    # structure rather than working with the raw sparse entries directly.
    print("Building User-Item Pivot Matrix...")
    R_df   = train_df.pivot(index='userId', columns='movieId', values='rating')
    users  = R_df.index.tolist()
    movies = R_df.columns.tolist()

    # -------------------------------------------------------------------------
    # STEP 3: Mean-Center the Rating Matrix
    # -------------------------------------------------------------------------
    # Subtract each user's average rating from all of their ratings.
    # This is a critical preprocessing step for two reasons:
    #
    #   1. BIAS REMOVAL: Some users are generous raters (always 4-5 stars),
    #      others are harsh (always 1-3 stars). Mean-centering removes this
    #      individual bias so the decomposition captures relative preferences,
    #      not absolute rating scales.
    #
    #   2. NEUTRAL IMPUTATION: After centering, NaN (unrated) cells are filled
    #      with 0. A 0 now means "unknown / neutral" rather than "zero stars",
    #      which is semantically correct and prevents unrated items from
    #      artificially pulling predictions toward zero.
    print("Mean Centering...")
    user_ratings_mean = R_df.mean(axis=1).values                        # shape: (num_users,)
    R_demeaned        = R_df.sub(user_ratings_mean, axis=0).fillna(0).values  # shape: (users × movies)

    # -------------------------------------------------------------------------
    # STEP 4: Truncated Singular Value Decomposition (SVD)
    # -------------------------------------------------------------------------
    # Decomposes R_demeaned into three matrices:
    #
    #   R_demeaned ≈ U · Σ · Vᵀ
    #
    #   U     (users  × k): latent user preference vectors
    #   sigma (k,)        : singular values — importance of each latent factor
    #   Vt    (k × movies): latent movie attribute vectors
    #
    # k=50 means we retain the 50 most important latent dimensions and discard
    # the rest. This truncation acts as regularisation — it forces the model to
    # capture broad generalizable patterns rather than overfitting to the noise
    # in individual sparse ratings.
    #
    # scipy's svds() is used instead of numpy's full SVD because it efficiently
    # computes only the top-k components without factorising the entire matrix,
    # which is much faster and memory-efficient on large sparse inputs.
    k_components = 50
    print(f"Running SVD with k={k_components}...")
    U, sigma, Vt = svds(R_demeaned, k=k_components)

    # svds returns sigma as a 1D array of singular values.
    # Convert to a (k × k) diagonal matrix for matrix multiplication.
    sigma = np.diag(sigma)

    # -------------------------------------------------------------------------
    # STEP 5: Reconstruct the Full Predicted Rating Matrix
    # -------------------------------------------------------------------------
    # Multiply the three factor matrices back together and add user means back
    # to reverse the mean-centering from Step 3.
    #
    #   R_predicted = U · Σ · Vᵀ + user_means
    #
    # The key result: every cell is now filled with a predicted rating,
    # including user-movie pairs that had no rating in the training data.
    # This dense matrix is what makes SVD so powerful for recommendation —
    # the baseline CF can only predict where training ratings exist.
    print("Reconstructing predicted ratings...")
    all_user_predicted_ratings = (
        np.dot(np.dot(U, sigma), Vt)     # low-rank reconstruction
        + user_ratings_mean.reshape(-1, 1) # add user means back (broadcast)
    )
    preds_df = pd.DataFrame(all_user_predicted_ratings, index=users, columns=movies)

    # Clip all predictions to the valid MovieLens rating scale [0.5, 5.0].
    # The reconstruction can occasionally produce values outside this range
    # due to the mathematical approximation of the truncated SVD.
    preds_df = preds_df.clip(lower=0.5, upper=5.0)

    # -------------------------------------------------------------------------
    # STEP 6: Rating Prediction — MAE and RMSE Evaluation
    # -------------------------------------------------------------------------
    # For each (user, movie) pair in the test set, look up the pre-computed
    # SVD prediction directly from the dense preds_df matrix.
    # Fall back to global mean only for users/movies unseen during training.
    print("\n--- Evaluating Rating Accuracy (MAE/RMSE) ---")
    actuals     = []
    predictions = []
    global_mean = train_df['rating'].mean()

    for _, row in test_df.iterrows():
        user  = row['userId']
        movie = row['movieId']

        if user in preds_df.index and movie in preds_df.columns:
            # Direct lookup from the dense reconstructed matrix
            pred = preds_df.loc[user, movie]
        else:
            # Fallback: user or movie not present in training data
            pred = global_mean

        actuals.append(row['rating'])
        predictions.append(pred)

    # MAE: average absolute error — intuitive "stars off target" metric
    # RMSE: penalises large errors more heavily than MAE due to squaring
    mae  = mean_absolute_error(actuals, predictions)
    rmse = np.sqrt(mean_squared_error(actuals, predictions))
    print(f"SVD MAE:  {mae:.4f}")
    print(f"SVD RMSE: {rmse:.4f}")

    # -------------------------------------------------------------------------
    # STEP 7: Top-10 Recommendation — Ranking Quality Evaluation
    # -------------------------------------------------------------------------
    # For each user, generate a ranked list of 10 movies they have NOT seen
    # in training, then check how many of those 10 appear in the test set.
    # These "hits" drive all four ranking metrics below.
    #
    # Because preds_df is fully dense, SVD can rank ALL unseen candidate items
    # with a meaningful predicted score — unlike the baseline which struggles
    # when the user-item overlap is sparse.
    print("\n--- Evaluating Top-10 Ranking Metrics ---")
    user_train_items = train_df.groupby('userId')['movieId'].apply(set).to_dict()
    user_test_items  = test_df.groupby('userId')['movieId'].apply(set).to_dict()

    precisions, recalls, ndcgs = [], [], []
    all_items = set(movies)   # full set of movies seen during training

    for user_id, test_items in tqdm(user_test_items.items()):

        # Skip users not present in the prediction matrix
        if user_id not in preds_df.index:
            continue

        # Candidate pool = all training movies MINUS what this user already rated.
        # We must never recommend a movie the user has already seen.
        train_items     = user_train_items.get(user_id, set())
        candidate_items = list(all_items - train_items)

        if not candidate_items:
            continue

        # Slice the user's predicted ratings for candidate movies only,
        # then sort descending and take the top 10
        user_preds     = preds_df.loc[user_id, candidate_items]
        top_candidates = user_preds.sort_values(ascending=False).head(10)
        top_item_ids   = top_candidates.index.tolist()

        # -----------------------------------------------------------------
        # Compute per-user ranking metrics
        # -----------------------------------------------------------------

        # hits[i] = 1 if the movie recommended at rank i+1 is in the test set
        hits = [1 if item in test_items else 0 for item in top_item_ids]

        # Precision@10: fraction of the 10 recommendations that were correct
        precision = sum(hits) / 10.0

        # Recall@10: fraction of the user's test movies that were surfaced
        recall    = sum(hits) / len(test_items)

        # NDCG@10: ranking-aware metric — hits at rank 1 score higher than
        # hits at rank 10 (see dcg_at_k / ndcg_at_k above)
        ndcg      = ndcg_at_k(hits, 10)

        precisions.append(precision)
        recalls.append(recall)
        ndcgs.append(ndcg)

    # -------------------------------------------------------------------------
    # STEP 8: Aggregate and Print Final Metrics
    # -------------------------------------------------------------------------
    avg_precision = np.mean(precisions)
    avg_recall    = np.mean(recalls)

    # F1-Measure: harmonic mean of precision and recall.
    # Uses harmonic mean (not arithmetic) to penalise large imbalances
    # between the two — a model with perfect precision but zero recall
    # gets F1 = 0, not 0.5.
    avg_f1   = 2 * (avg_precision * avg_recall) / (avg_precision + avg_recall) \
               if (avg_precision + avg_recall) > 0 else 0
    avg_ndcg = np.mean(ndcgs)

    print("\n========= SVD TOP-10 RECOMMENDATION METRICS =========")
    print(f"Precision@10 : {avg_precision:.4f}")
    print(f"Recall@10    : {avg_recall:.4f}")
    print(f"F1-Measure   : {avg_f1:.4f}")
    print(f"NDCG@10      : {avg_ndcg:.4f}")
    print("=====================================================")


# -----------------------------------------------------------------------------
# ENTRY POINT
# -----------------------------------------------------------------------------
if __name__ == '__main__':
    run_custom_svd()